EKEC-crew/BE

src/crew/search/search/controller/search.controller.js

---
- *** Swagger 문서 예시 값 수정
- #16 
---
- 현재 작업 브랜치: refactor/hoshi/crew-search-filter-modify-swagger
---
- *** 서버 실행 후 Swagger 확인
-

:recycle: Refactor: 크루 검색 필터 #16

---

.github/workflows/deploy-main.yml

---
- *** CI/CD 파이프라인 수정
- #21 
---
- 병합 대상 브랜치:develop
- 현재 작업 브랜치:bug/hoshi/ci-cd-pipeline
---
- ***
-

🐛Fix: CI/CD 파이프라인 수정

---

src/crew/search/search/controller/search.controller.js

---
- *** Swagger 예시 수정
- #33 
---
- 현재 작업 브랜치: refactor/hoshi/crew-search-filter-new-replace-example
---
- ***
-

♻️Refactor: 크루 검색 필터 (new) #33

---

prisma/schema.prisma

---
- 크루 지원 폼 테이블
- 크루 지원 답변1 테이블
- 크루 지원 답변2 테이블
- 크루 만들기 관련 테이블 업데이트
---
- 현재 작업 브랜치: feature/darong/prisma
---
- npm exec prisma migrate dev
- npm exec prisma generate
-

:recycle: Refactor: prisma update

---

package-lock.json
package.json
prisma/schema.prisma
src/config/aws/s3.js
src/crew/creation/controller/creation.controller.js
src/crew/creation/dto/request/creation.request.dto.js
src/crew/creation/dto/response/creation.response.dto.js
src/crew/creation/repository/creation.repository.js
src/crew/creation/route/creation.route.js
src/crew/creation/service/creation.service.js
src/crew/image/service/image.service.js
src/error.js
src/index.js

---
- *** 크루 만들기 기능 추가
- #53 
---
- 현재 작업 브랜치: feature/hoshi/create-crew
---
- *** Swagger, Postman
-

✨Feat: 크루 만들기 #53

---

package-lock.json
package.json
prisma/schema.prisma
src/config/aws/s3.js
src/crew/creation/controller/creation.controller.js
src/crew/creation/dto/request/creation.request.dto.js
src/crew/creation/dto/response/creation.response.dto.js
src/crew/creation/repository/creation.repository.js
src/crew/creation/route/creation.route.js
src/crew/creation/service/creation.service.js
src/crew/image/service/image.service.js
src/crew/list/controller/list.controller.js
src/crew/list/dto/response/list.response.dto.js
src/crew/list/repository/list.repository.js
src/crew/list/route/list.route.js
src/crew/list/service/list.service.js
src/error.js
src/index.js

---
- *** 크루 만들기 기능 추가
- *** prisma 스키마 수정
- #53 
---
---
- ***
-

✨Feat: 크루 만들기, prisma 스키마 구조 변경에 대한 반영 PR

---

prisma/schema.prisma
src/crew/page/plan/controller/plan.controller.js
src/crew/page/plan/dto/request/plan.request.dto.js
src/crew/page/plan/dto/response/plan.response.dto.js
src/crew/page/plan/repository/plan.repository.js
src/crew/page/plan/route/plan.route.js
src/crew/page/plan/service/plan.service.js

---
- ***
- #
---
- 현재 작업 브랜치: feature/hyunjun/crew-plan
---
- ***
-

✨ 크루 댓글 생성 기능 구현

---

prisma/schema.prisma

---
- ***
- #
---
- 병합 대상 브랜치:
- 현재 작업 브랜치:
---
- ***
-

Schema.prisma 오류 해결

---

src/crew/page/plan/controller/plan.controller.js
src/crew/page/plan/dto/request/plan.request.dto.js
src/crew/page/plan/dto/response/plan.response.dto.js
src/crew/page/plan/route/plan.route.js

---
- ***
- #
---
- 병합 대상 브랜치:
- 현재 작업 브랜치:
---
- ***
-

Swagger 오류 해결

---

src/crew/page/plan/controller/plan.controller.js

---
- ***
- #
---
- 병합 대상 브랜치:
- 현재 작업 브랜치:
---
- ***
-

🐛 404, 202 응답 간소화

---

src/crew/creation/controller/creation.controller.js
src/crew/creation/service/creation.service.js
src/image/controller/image.controller.js
src/image/dto/request/image.request.dto.js
src/image/dto/response/image.response.dto.js
src/image/route/image.route.js
src/image/service/image.service.js
src/utils/s3.js

---
- *** s3 이미지 업로드 공통 함수 구현 / 리펙토링
- #92 
---
- 현재 작업 브랜치: refactor/hoshi/s3-upload-common-function
---
- *** Swagger
-

:recycle: Refactor: s3로 이미지 업로드 공통함수 리펙토링 #92 - 완료

---

src/crew/creation/controller/creation.controller.js
src/crew/creation/repository/creation.repository.js
src/crew/creation/service/creation.service.js
src/error.js

---
- ***
- #
---
- 현재 작업 브랜치: refactor/hoshi/crew-creation-1
---
- ***
-

♻️Refactor: 크루 생성 API #100

---

src/crew/creation/controller/creation.controller.js

---
- ***
- #
---
- 현재 작업 브랜치: bug/hoshi/fix-swagger
---
- ***
-

🐛Fix: Swagger 수정 #103

---

src/crew/page/post/repository/post.repository.js
src/crew/page/post/service/post.service.js

:recycle: Refactor: console add

---

src/crew/page/post/dto/response/post.response.dto.js
src/index.js

---
- post.repsonse.dto.js 변경
- #
---
---
- ***
-

:recycle: Refactor: time set Seoul

---

prisma/schema.prisma
src/crew/apply/controller/apply.controller.js
src/crew/apply/dto/request/apply.request.dto.js
src/crew/apply/dto/response/apply.response.dto.js
src/crew/apply/repository/apply.repository.js
src/crew/apply/route/apply.route.js
src/crew/apply/service/apply.service.js
src/crew/route/crew.route.js

---
- 특정 크루 지원하기
- 특정 크루 특정 지원서 확인하기 API
- 특정 크루 특정 지원서 승인/거절하기
- https://github.com/EKEC-crew/BE/issues/67
---
- 현재 작업 브랜치: feature/durian/crew-apply-new
---
- swagger 활용
- 크루 만들기가 선행되어야지 테스트 가능

✨ Feat: 특정 크루 지원 기능

---

prisma/schema.prisma

---
- ***
- #
---
- 병합 대상 브랜치:
- 현재 작업 브랜치:
---
- ***
-

Schema.prisma 수정

---

prisma/schema.prisma
src/crew/page/plan/controller/plan.controller.js
src/crew/page/plan/dto/request/plan.request.dto.js
src/crew/page/plan/repository/plan.repository.js
src/crew/page/plan/route/plan.route.js
src/crew/page/plan/service/plan.service.js

---
- ***
- #
---
- 병합 대상 브랜치:
- 현재 작업 브랜치:
---
- ***
-

크루 일정 CRUD 및 댓글 CRUD 테스트 완료

---

src/crew/apply/controller/apply.controller.js
src/crew/apply/dto/response/apply.response.dto.js
src/crew/apply/repository/apply.repository.js
src/crew/apply/route/apply.route.js
src/crew/apply/service/apply.service.js

---
- 특정 크루 지원서 조회 API 추가
- https://github.com/EKEC-crew/BE/issues/124
---
- 현재 작업 브랜치: feature/durian/crew-apply-new2
---
- swagger 테스트 진행
-

:sparkles:Feat: 특정 크루 지원서 조회

---

src/auth/repository/auth.repository.js
src/auth/scheduler/auth.scheduler.js
src/auth/service/auth.service.js
src/crew/creation/controller/creation.controller.js
src/crew/creation/dto/request/creation.request.dto.js
src/crew/creation/service/creation.service.js

---
- *** 가입 미완료된 계정 정리 스케줄러 추가
- *** 크루 가입기능 인증 미들웨어 연결
- #
---
- 현재 작업 브랜치: feature/hoshi/auth-feature
---
- *** Swagger
-

✨Feat: 크루생성 인증 연결, 가입 미 완료 계정 정리 스케줄러 구현 #149

---

src/crew/creation/controller/creation.controller.js
src/crew/creation/service/creation.service.js

---
- *** 크루 생성 이미지 필수 옵션 제거
- #152 
---
- 현재 작업 브랜치: refactor/hoshi/crew-creation-remove-required-banner
---
- *** swagger
-

♻️Refactor: 크루 생성 이미지 필수 옵션 제거 #152

---

src/crew/apply/applicants/controller/applicants.controller.js
src/crew/apply/applicants/dto/response/applicants.response.dto.js

---
- 지원자 목록에 applyId 응답 필드 추가
- #
---
- 현재 작업 브랜치: feature/durian/crew-apply-applicants
---
- Swagger 활용
-

:recycle:Refactor: 지원자 목록에 applyId 응답 필드 추가

---

src/crew/page/post/controller/post.controller.js
src/crew/page/post/dto/request/post.request.dto.js
src/crew/page/post/route/post.route.js
src/crew/page/post/service/post.service.js
src/error.js

---
- 크루 게시글 관련 인가 처리 필요 기능에 인증 미들웨어 추가
- 크루 댓글 관련 인가 처리 필요 기능에 인증 미들웨어 추가
- #
---
---
- swagger 에 (로그인 필요) 기능 사용시 로그인 후 진행
- 해당 크루에 속하지 않은 유저, 작성자가 아닌 유저 등 주의

:recycle: Refactor: 로그인 필요 기능에 인증 미들웨어 추가

---

src/crew/page/member/controller/member.controller.js
src/crew/page/member/dto/request/member.request.dto.js
src/crew/page/member/dto/response/member.response.dto.js
src/crew/page/member/repository/member.repository.js
src/crew/page/member/route/member.route.js
src/crew/page/member/service/member.service.js

---
- 크루 멤버 리스트 조회, 승격, 제외, 방출 기능시 인가처리
- #
---
- 현재 작업 브랜치: feature/darong/crew-page-member
---
- swagger 테스트시 로그인 후 사용할 것
-

:recycle: Refactor: add AccessToken middleware logic

---

src/auth/controller/auth.controller.js

---
- *** 토큰 쿠키의 samesite 옵션을 none으로 설정하여 프론트에서 정상적으로 이용가능하도록 설정
- #167 
---
- 병합 대상 브랜치:develop
- 현재 작업 브랜치:bug/hoshi/fix-cookie-same-site-option
---
- ***
-

:bug: Fix: 프론트엔드의 토큰 사용 버그 수정 #167

---

src/auth/controller/auth.controller.js
src/index.js

---
- *** 토큰 설정 변경
- #170 
---
- 현재 작업 브랜치: bug/hoshi/fix-token-bug
---
- ***
-

:bug: Fix: 프론트엔드의 토큰 사용 버그 수정

---

src/auth/controller/auth.controller.js
src/index.js

---
- ***
- #171 
---
---
- ***
-

✨ develop 변경 사항 main 반영

---

src/auth/controller/auth.controller.js
src/auth/middleware/auth.middleware.js
src/crew/creation/controller/creation.controller.js
src/error.js
src/index.js

:sparkles: develop 변경사항 main 반영

---

src/crew/page/member/controller/member.controller.js
src/crew/page/member/dto/request/member.request.dto.js
src/crew/page/member/dto/response/member.response.dto.js
src/crew/page/member/repository/member.repository.js
src/crew/page/member/route/member.route.js
src/crew/page/member/service/member.service.js

---
- ***
- #
---
- 현재 작업 브랜치: feature/darong/crew-page-member
---
- swagger CrewMember 의 api 확인
-

:sparkles: Feat: create addCrewMember API(dev)

---

prisma/schema.prisma
src/crew/page/role/controller/role.controller.js
src/crew/page/role/dto/request/role.request.dto.js
src/crew/page/role/dto/response/role.response.dto.js
src/crew/page/role/repository/role.repository.js
src/crew/page/role/route/role.route.js
src/crew/page/role/service/role.service.js
src/crew/page/route/page.route.js

---
- ***
- #
---
- 현재 작업 브랜치: feature/darong/crew-page-role
---
- swagger Crew Role 확인
-

:sparkles: Feat: 특정 크루 멤버 역할 반환 기능

---

prisma/schema.prisma
src/crew/page/plan/controller/plan.controller.js
src/crew/page/plan/dto/request/plan.request.dto.js
src/crew/page/plan/dto/response/plan.response.dto.js
src/crew/page/plan/repository/plan.repository.js
src/crew/page/plan/route/plan.route.js
src/crew/page/plan/service/plan.service.js
src/error.js

---
- ***
- #
---
- 현재 작업 브랜치: feature/hyunjun/crew-plan
---
- ***
-

✨ 크루 일정 신청 및 좋아요 기능 구현

---

src/crew/page/info/controller/info.controller.js
src/crew/page/info/dto/response/info.response.dto.js
src/crew/page/info/repository/info.repository.js
src/crew/page/info/service/info.service.js

---
- crewCapacity -> memberCount
- maxCapacity -> crewCapacity
- #
---
- 현재 작업 브랜치: feature/darong/crew-page-info
---
- ***
-

:recycle: Refactor: 응답값 수정

---

prisma/schema.prisma
src/crew/page/plan/controller/plan.controller.js
src/crew/page/plan/dto/request/plan.request.dto.js
src/crew/page/plan/dto/response/plan.response.dto.js
src/crew/page/plan/repository/plan.repository.js
src/crew/page/plan/route/plan.route.js
src/crew/page/plan/service/plan.service.js
src/error.js

This reverts commit b302556648806c789e2ff645afe312630da6fd9b.
---
- ***
- #
---
- 병합 대상 브랜치:
- 현재 작업 브랜치:
---
- ***
-

Reapply "✨ 크루 일정 신청 및 좋아요 기능 구현"

---

src/crew/page/member/controller/member.controller.js

---
- 스웨거 문법 변경
- #
---
- 현재 작업 브랜치: feature/darong/crew-page-member
---
- ***
-

:recycle: Refactor: swagger update

---

src/crew/search/search/controller/search.controller.js

---
- ***
- #
---
- 현재 작업 브랜치: bug/hoshi/fix-swagger-3
---
- ***
-

swagger 수정

---

src/crew/page/plan/repository/plan.repository.js

---
- ***
- #
---
- 병합 대상 브랜치:
- 현재 작업 브랜치:
---
- ***
-

:recycle: 좋아요개수랑 댓글 개수 추가

---

src/crew/page/plan/repository/plan.repository.js
src/crew/search/search/controller/search.controller.js

---
- ***
- #
---
- 병합 대상 브랜치:
- 현재 작업 브랜치:
---
- ***
-

:recycle: 응답 dto에 좋아요개수랑 댓글 개수 추가 

---

prisma/schema.prisma
src/crew/page/plan/dto/response/plan.response.dto.js
src/crew/page/plan/repository/plan.repository.js

---
- ***
- #
---
- 병합 대상 브랜치:
- 현재 작업 브랜치:
---
- ***
-

:recycle: Schema.prisma 수정 및 에러 해결

---

package-lock.json
package.json
prisma/schema.prisma
src/alarm/controller/alarm.controller.js
src/alarm/dto/request/alarm.request.dto.js
src/alarm/dto/response/alarm.response.dto.js
src/alarm/repository/alarm.repository.js
src/alarm/repository/alarm.temp.repository.js
src/alarm/route/alarm.route.js
src/alarm/service/alarm.service.js
src/alarm/service/listener/alarm.listener.js
src/auth/service/auth.service.js
src/config/eventEmitter/eventEmitter.js
src/error.js
src/index.js

---
- *** 알림 기능 추가
- #227 
---
- 현재 작업 브랜치: feature/hoshi/alarm-feature
---
- *** Swagger
-

✨Feat: 알림 기능 추가 #227

---

package-lock.json
package.json
prisma/schema.prisma
src/alarm/controller/alarm.controller.js
src/alarm/dto/request/alarm.request.dto.js
src/alarm/dto/response/alarm.response.dto.js
src/alarm/repository/alarm.repository.js
src/alarm/repository/alarm.temp.repository.js
src/alarm/route/alarm.route.js
src/alarm/service/alarm.service.js
src/alarm/service/listener/alarm.listener.js
src/auth/service/auth.service.js
src/config/eventEmitter/eventEmitter.js
src/crew/apply/controller/apply.controller.js
src/crew/apply/dto/request/apply.request.dto.js
src/crew/apply/dto/response/apply.response.dto.js
src/crew/apply/middleware/crew.middleware.js
src/crew/apply/repository/apply.repository.js
src/crew/apply/route/apply.route.js
src/crew/apply/service/apply.service.js
src/error.js
src/index.js

---
- *** 알림 기능 추가
- #227 
---
---
- ***
-

✨ develop 변경사항 반영

---

src/crew/page/plan/controller/plan.controller.js
src/crew/page/plan/dto/response/plan.response.dto.js
src/crew/page/plan/service/plan.service.js

---
- ***
- #
---
- 병합 대상 브랜치:
- 현재 작업 브랜치:
---
- ***
-

:recycle: isLiked, isApplied 필드 추가

---

src/crew/list/controller/list.controller.js
src/crew/list/dto/response/list.response.dto.js
src/crew/list/repository/list.repository.js

---
- 인기/최신순 크루 정렬시 짧은 소개글 introduction → content 로 변경
- #
---
- 현재 작업 브랜치: refactor/durian/crew-list
---
- Swagger 테스트
-

:recycle:Refactor: 크루 리스트 조회 응답 변경

---

src/crew/apply/dto/response/apply.response.dto.js
src/crew/apply/repository/apply.repository.js

---
- 체크박스/장문형 문항 구분
- 체크박스 문항에서 기타를 추가하여 적은 답변 분리
- https://github.com/EKEC-crew/BE/issues/246
---
- 현재 작업 브랜치: refactor/durian/crew-apply-3
---
- Swagger
-

♻️Refactor: 특정 크루 특정 지원서 조회 응답 수정

---

src/crew/list/dto/response/list.response.dto.js

---
- 인기/신규 크루 조회시 region이 선택되지 않은 크루 존재하면 오류 발생 -> 지역을 선택되지 않은 크루 존재시 서울 전지역으로 기본값 사용
- 
- https://github.com/EKEC-crew/BE/issues/249
---
- 현재 작업 브랜치: bug/durian/crew-apply
---
- swagger
-

🐛Fix: 인기/신규 크루 조회시 오류 수정

---

src/crew/apply/dto/response/apply.response.dto.js
src/crew/apply/repository/apply.repository.js

---
- ***
- #
---
- 병합 대상 브랜치:
- 현재 작업 브랜치:
---
- ***
-

🐛Fix: 특정 크루 특정 지원서 조회 오류 수정 (2)

---

src/crew/apply/dto/response/apply.response.dto.js

---
- ***
- #
---
- 병합 대상 브랜치:
- 현재 작업 브랜치:
---
- ***
-

♻️ Refactor: 특정 크루 특정 지원서 응답 수정

---

src/crew/page/plan/controller/plan.controller.js
src/crew/page/plan/dto/response/plan.response.dto.js
src/crew/page/plan/repository/plan.repository.js
src/crew/page/plan/route/plan.route.js
src/crew/page/plan/service/plan.service.js

---
- ***
- #
---
- 병합 대상 브랜치:
- 현재 작업 브랜치:
---
- ***
-

:sparkles: 다가오는 일정 api 구현

---

prisma/schema.prisma
src/alarm/controller/alarm.controller.js
src/alarm/service/alarm.service.js
src/config/eventEmitter/eventEmitter.js
src/crew/page/plan/service/plan.service.js

---
- *** 알림기능 버그 수정
- #271 
---
- 현재 작업 브랜치: bug/hoshi/fix-alarm
---
- *** Swagger
-

🐛Fix: 알림 기능 수정 #271

---

src/crew/route/crew.route.js

---
- crew-apply-list 라우트 경로 수정
- https://github.com/EKEC-crew/BE/issues/272
---
- 현재 작업 브랜치: bug/durian/crew-apply-list
---
- swagger
-

🐛Fix: crew-apply-list 라우트 경로 수정

---

src/crew/creation/repository/creation.repository.js
src/crew/search/search/repository/search.repository.js
src/crew/search/search/service/search.service.js

---
- *** 별점 기능 수정
- #274 
---
- 현재 작업 브랜치: refactor/hoshi/dummy-star-point
---
- *** Swagger
-

♻️Refactor: 별점 기능 수정 #274

---

src/crew/page/plan/dto/response/plan.response.dto.js
src/crew/page/plan/repository/plan.repository.js

---
- ***
- #
---
- 병합 대상 브랜치:
- 현재 작업 브랜치:
---
- ***
-

:recycle: writerImage 필드 추가

---

src/crew/page/post/service/post.service.js

---
- 크루 게시글 댓글 서비스 로직 변경
- #
---
---
- ***
-

:recycle: Refactor: 서비스 버그 수정

---

prisma/schema.prisma
src/crew/creation/controller/creation.controller.js

---
- *** 크루 인원 제한없음 버그 수정
- #285 
---
- 현재 작업 브랜치: bug/hoshi/crew-capacity-limit
---
- *** Swagger
-

🐛Fix: 크루 제한 인원 수정 #285

---

prisma/schema.prisma
src/crew/creation/controller/creation.controller.js
src/crew/page/post/service/post.service.js

---
- *** 크루 인원제한 버그 수정
- #285 
---
---
- ***
-

✨ develop변경사항 main 반영

---

src/crew/apply/joined/controller/joined.controller.js
src/crew/apply/joined/dto/response/joined.response.dto.js
src/crew/apply/joined/repository/joined.repository.js
src/crew/apply/joined/route/joined.route.js
src/crew/apply/joined/service/joined.service.js
src/crew/apply/route/apply.route.js

---
- 현재 가입되어 있는 크루 목록 조회 추가
- https://github.com/EKEC-crew/BE/issues/292
---
- 현재 작업 브랜치: feature/durian/crew-apply-joined
---
- Swagger
-

✨Feat: 현재 가입되어 있는 크루 목록 조회

---

src/crew/page/plan/repository/plan.repository.js

---
- ***
- #
---
- 병합 대상 브랜치:
- 현재 작업 브랜치:
---
- ***
-

:recycle: 일정 댓글 오름차순으로 변경

---

src/auth/oauth/strategy/google.js
src/auth/oauth/strategy/kakao.js
src/auth/oauth/strategy/naver.js
src/config/oauth/passport.js
src/crew/page/notice/notice.controller.js

- [O] 의존성, 환경 변수, 빌드 관련 코드 업데이트
---
- 공지 권한 관련 api 리팩토링
- #
---
- 현재 작업 브랜치:
---
- ***
-

:recycle:공지 api 리팩토링

---

src/auth/oauth/strategy/google.js
src/auth/oauth/strategy/kakao.js
src/auth/oauth/strategy/naver.js
src/config/oauth/passport.js
src/crew/page/notice/notice.controller.js
src/crew/page/plan/repository/plan.repository.js

- [O] 의존성, 환경 변수, 빌드 관련 코드 업데이트
---
- 공지 권한관련 api 코드 리팩토링
- #
---
- 현재 작업 브랜치:
---
- ***
-

공지 권한관련 api 코드 리팩토링

---

src/crew/creation/list/controller/list.controller.js
src/crew/creation/list/dto/response/list.response.dto.js
src/crew/creation/list/repository/list.repository.js
src/crew/creation/list/route/list.route.js
src/crew/creation/list/service/list.service.js
src/crew/creation/route/creation.route.js
src/crew/route/crew.route.js

---
- 내가 만든 크루 목록 조회 추가
- https://github.com/EKEC-crew/BE/issues/297
---
- 현재 작업 브랜치: feature/durian/creation-list
---
- 스웨거
-

✨Feat: 내가 만든 크루 목록 조회

---

src/crew/page/post/controller/post.controller.js
src/crew/page/post/dto/request/post.request.dto.js
src/crew/page/post/dto/response/post.response.dto.js
src/crew/page/post/repository/post.repository.js
src/crew/page/post/route/post.route.js
src/crew/page/post/service/post.service.js

---
- 게시글 상세조회시 사용자 좋아요 여부 추가
- #
---
---
- ***
-

:recycle: Refactor: isLiked 사용자 좋아요 여부 추가

---

src/auth/controller/auth.controller.js
src/auth/dto/response/auth.response.dto.js

---
- *** 프로필 설정 응답값 수정 (이미지 경로 추가)
- #319 
---
- 현재 작업 브랜치: refactor/hoshi/modify-profile-setting-response
---
- ***
-

♻️Refactor: 프로필 설정 반환값 수정 #319

---

prisma/schema.prisma

---
- 모든 테이블에 delete Cascade 삭제 설정
- #
---
---
- ***
-

:recycle: Refactor: prisma 수정

---

prisma/schema.prisma

- onDelete : setNull 또는 Cascade 설정
---

:bug: Fix: prisma 긴급 수정

---

prisma/schema.prisma

- onDelete : setNull 또는 Cascade 설정
---

:bug: Fix: 프리즈마 긴급 수정

---

prisma/schema.prisma

:bug: Fix: 프리즈마 수정

---

src/crew/page/member/repository/member.repository.js
src/crew/page/member/service/member.service.js

---
- 크루원 방출시 해당 크루원에게 알림 전송 기능 적용
- #
---
- 현재 작업 브랜치: feature/darong/crew-page-member
---
- swagger 크루원 방출해보기
-

:sparkles: Feat: 크루원 방출 알림  기능 적용

---

src/crew/search/search/service/search.service.js

---
- *** 검색 크루 최대 인원 필터 버그 수정
- #334 
---
- 병합 대상 브랜치:develop
- 현재 작업 브랜치:bug/hoshi/crew-search-capacity-bug
---
- ***Swagger
-

🐛Fix: 검색 크루 최대 인원 필터 버그 수정 #334

---

src/crew/page/post/service/post.service.js

---
- 알림에 crewId 추가
- #
---
---
- ***
-

:recycle: Refactor: 게시글 좋아요, 댓글 알림 기능 수정

---

src/crew/page/plan/controller/plan.controller.js
src/crew/page/plan/repository/plan.repository.js
src/crew/page/plan/service/plan.service.js

---
- ***
- #
---
- 병합 대상 브랜치:
- 현재 작업 브랜치:
---
- ***
-

:recycle: 크루장도 다가오는 일정 리스트 조회 가능하게끔 수정
